### PR TITLE
Fixed url to github

### PR DESCRIPTION
**Pull request by repejota**
Fixed url to github in the bottom

### CODE REVIEW

**Comment by ifraixedes** [comment]
One thing, even though the result is the same you may want to use the url with the corresponding capitalization as [it's currently in the new web site](https://github.com/BarcelonaJS/barcelonajs.github.io/blob/development/src/partials/footer.html#L17)

**Comment by ifraixedes** [comment]
@repejota  sorry I went to fast and clicked the wrong button when posted the comment; I've reopen it.

**Comment by repejota** [comment]
Fixed! :smile:

**Comment by ifraixedes** [comment]
Cool,

cool

**Pull request merged**
